import java.io.Serializable;

public enum Distrito implements Serializable {

    AVEIRO, BEJA, BRAGA, BRAGANCA, CASTELOBRANCO, COIMBRA,
    EVORA, FARO, GUARDA, LEIRIA, LISBOA, PORTALEGRE, PORTO,
    SANTAREM, SETUBAL, VIANACASTELO, VILAREAL, VISEU;

}
